backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "public/assets/templates/images"
public_folder: "/assets/templates/images"
collections:
  - name: "himalayanProfile"
    label: "Trek Name"
    folder: "src/himalayanProfile"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Title", name: "titleShort", widget: "string" }
      - { label: "Heading", name: "heading", widget: "string" }
      - { label: "Sub Heading", name: "subHeading", widget: "string" }
      - { label: "Trek Price", name: "trekPrice", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Banner Image", name: "bannerImage", widget: "image" }
      - { label: "Banner Image Alt", name: "imageAlt", widget: "string" }
      - { label: "Brief Description", name: "description", widget: "string" }
      - { label: "Section Overview Heading", name: "sectionOverview", widget: "string" }
      - { label: "Section Overview Body", name: "sectionOverviewBullets", widget: "list" }
      - { 
          label: "Image Carousel", 
          name: "images", 
          widget: "image", 
          choose_url: true, 
          default: "/assets/templates/images/profile/kedarkantha-peak-trek/kedarkantha-peak-trek-1.jpg", 
          media_library: 
            config: 
              multiple: true
        }

