backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "public/assets/templates/images"
public_folder: "/assets/templates/images"
collections:
  - name: "himalayanProfile"
    label: "Trek Name"
    folder: "src/himalayanProfile"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Title", name: "titleShort", widget: "string" }
      - { label: "Heading", name: "heading", widget: "string" }
      - { label: "Sub Heading", name: "subHeading", widget: "string" }
      - { label: "Trek Price", name: "trekPrice", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Banner Image", name: "bannerImage", widget: "image" }
      - { label: "Banner Image Alt", name: "imageAlt", widget: "string" }
