backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "public/assets/templates/images"
public_folder: "/assets/templates/images"
collections:
  - name: "himalayanProfile"
    label: "Trek Name"
    folder: "src/himalayanProfile"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Title", name: "titleShort", widget: "string" }
      - { label: "Heading", name: "heading", widget: "string" }
      - { label: "Sub Heading", name: "subHeading", widget: "string" }
      - { label: "Trek Price", name: "trekPrice", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Banner Image", name: "bannerImage", widget: "image" }
      - { label: "Banner Image Alt", name: "imageAlt", widget: "string" }
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        choose_url: true
        default: "/uploads/chocolate-dogecoin.jpg"
        media_library:
          config:
            multiple: true

      - { label: "Brief Description", name: "description", widget: "string" }
      - { label: "Section Overview Heading", name: "sectionOverview", widget: "string" }
      - { label: "Section Overview Bullets", name: "sectionOverviewBullets", widget: "list" }
      - { label: "Section Overview Description", name: "sectionOverviewDescription", widget: "text"}
      - { label: "Section Short Itinerary", name: "shortItinerary", widget: "string" }
      - { label: "Section Short Itinerary Bullets", name: "sectionShortItineraryBullets", widget: "list" }
      - { label: "Section Weather", name: "sectionWeather", widget: "string" }
      - { label: "Section Weather Description", name: "sectionWeatherDescription", widget: "text" }
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        fields:
          - { label: "Source", name: "src", widget: "image" }
          - { label: "Alt Text", name: "alt", widget: "string" }
        default:
          - { src: "/assets/templates/images/profile/kedarkantha-peak-trek/kedarkantha-peak-trek-2.jpg", alt: "Tennis" }
          - { src: "/assets/templates/images/profile/kedarkantha-peak-trek/kedarkantha-peak-trek-3.jpg", alt: "Football" }